//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int GovernateId { get; set; }
        public int CityId { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Details { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual City City { get; set; }
        public virtual Governate Governate { get; set; }
    }
}
