//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public Cart()
        {
            this.CartDetails = new HashSet<CartDetail>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<int> DeliveryId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> DeliveryState { get; set; }
        public decimal Total { get; set; }
        public Nullable<int> GetwayId { get; set; }
        public bool IsShow { get; set; }
    
        public virtual ICollection<CartDetail> CartDetails { get; set; }
        public virtual delivery delivery { get; set; }
        public virtual GetWay GetWay { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
