//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFContext : DbContext
    {
        public EFContext()
            : base("name=EFContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<CartDetail> CartDetails { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<delivery> deliveries { get; set; }
        public virtual DbSet<Enquiry> Enquiries { get; set; }
        public virtual DbSet<GetWay> GetWays { get; set; }
        public virtual DbSet<Governate> Governates { get; set; }
        public virtual DbSet<HomeDetail> HomeDetails { get; set; }
        public virtual DbSet<LestCategory> LestCategories { get; set; }
        public virtual DbSet<MainCategory> MainCategories { get; set; }
        public virtual DbSet<PrivilegeAction> PrivilegeActions { get; set; }
        public virtual DbSet<PrivilegeCategory> PrivilegeCategories { get; set; }
        public virtual DbSet<Privilege> Privileges { get; set; }
        public virtual DbSet<ProductImage> ProductImages { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductShow> ProductShows { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<RulePrivilege> RulePrivileges { get; set; }
        public virtual DbSet<Rule> Rules { get; set; }
        public virtual DbSet<SliderImage> SliderImages { get; set; }
        public virtual DbSet<Speciality> Specialities { get; set; }
        public virtual DbSet<SysEmail> SysEmails { get; set; }
        public virtual DbSet<SysNew> SysNews { get; set; }
        public virtual DbSet<UserOperation> UserOperations { get; set; }
        public virtual DbSet<UserOperationType> UserOperationTypes { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ViewControl> ViewControls { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<FAQ> FAQs { get; set; }
    }
}
