//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enquiry
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Question { get; set; }
        public string Replay { get; set; }
        public int ProductId { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
