//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class LestCategory
    {
        public LestCategory()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public int MainCategoryId { get; set; }
        public int CategoryId { get; set; }
        public string ImageUrl { get; set; }
        public string Name { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual MainCategory MainCategory { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
