//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainCategory
    {
        public MainCategory()
        {
            this.Categories = new HashSet<Category>();
            this.LestCategories = new HashSet<LestCategory>();
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<LestCategory> LestCategories { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
