//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilege
    {
        public Privilege()
        {
            this.PrivilegeActions = new HashSet<PrivilegeAction>();
            this.RulePrivileges = new HashSet<RulePrivilege>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int PrivilegeCategoryId { get; set; }
        public int PrivilegeOrder { get; set; }
    
        public virtual ICollection<PrivilegeAction> PrivilegeActions { get; set; }
        public virtual PrivilegeCategory PrivilegeCategory { get; set; }
        public virtual ICollection<RulePrivilege> RulePrivileges { get; set; }
    }
}
