//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Enquiries = new HashSet<Enquiry>();
            this.ProductImages = new HashSet<ProductImage>();
            this.ProductShows = new HashSet<ProductShow>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int BrandId { get; set; }
        public int MainCategoryId { get; set; }
        public int LestCategoryId { get; set; }
        public int CategoryId { get; set; }
        public string Berif { get; set; }
        public string Details { get; set; }
        public decimal SalePrice { get; set; }
        public decimal DiscountPrice { get; set; }
        public string ImageUrl { get; set; }
        public bool DiscountPercent { get; set; }
        public int AvailableQuntaty { get; set; }
        public string Notes { get; set; }
        public System.DateTime Time { get; set; }
        public bool IsHome { get; set; }
        public byte Evalute { get; set; }
        public bool BestSeller { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Enquiry> Enquiries { get; set; }
        public virtual LestCategory LestCategory { get; set; }
        public virtual MainCategory MainCategory { get; set; }
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        public virtual ICollection<ProductShow> ProductShows { get; set; }
    }
}
