//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class RulePrivilege
    {
        public int Id { get; set; }
        public int RuleId { get; set; }
        public int PrivilegeId { get; set; }
    
        public virtual Privilege Privilege { get; set; }
        public virtual Rule Rule { get; set; }
    }
}
